// <auto-generated />
using System;
using GestorPostgreSQL.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GestorPostgreSQL.Server.Migrations
{
    [DbContext(typeof(GestorDbContext))]
    [Migration("20220118191655_Gestor")]
    partial class Gestor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("GestorPostgreSQL.Shared.Modelos.Empleado", b =>
                {
                    b.Property<string>("codigo")
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .HasColumnType("text");

                    b.Property<string>("estudios")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechanacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.HasKey("codigo");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("GestorPostgreSQL.Shared.Modelos.Entidad", b =>
                {
                    b.Property<string>("codigo")
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<string>("sector")
                        .HasColumnType("text");

                    b.HasKey("codigo");

                    b.ToTable("Entidades");
                });

            modelBuilder.Entity("GestorPostgreSQL.Shared.Modelos.EntidadEmpleado", b =>
                {
                    b.Property<string>("codigoentidad")
                        .HasColumnType("text");

                    b.Property<string>("anios")
                        .HasColumnType("text");

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<string>("cargo")
                        .HasColumnType("text");

                    b.Property<string>("codigoempleado")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaingresp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fecharetiro")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("codigoentidad");

                    b.ToTable("EntidadEmpleados");
                });
#pragma warning restore 612, 618
        }
    }
}
